### ISSUE TITLE
Migration to version 9.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/connector#129]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Modules to migrate
- [x] connector (@lmignon) PR #169 
  - [x] make the module installable (@lmignon)
  - [x] remove the old workers code (@lmignon)
  - [x] integrate PR #165 (@lmignon) 
- [X] connector_base_product - https://github.com/OCA/connector/pull/180

**Comment by jaredkipe** [comment]
Does anything actually need to be done with this?  It seems like the big changes to order workflow would only really affect connector-ecommerce and related modules. 

I have changed it to installable and installed it without any issues other than a missing image thumbnail.

**Comment by guewen** [comment]
It should work as is but we want to take the opportunity of the version
change for  refactoring, including removal of the old workers.

**Comment by dansanti** [comment]
@jaredkipe hi! how do you solve in a clean installation?

``` xml

File "/usr/lib/python2.7/dist-packages/openerp/addons/connector/checkpoint/checkpoint.py", line 51, in _compute_record
    check.record = check.model_id.model + ',' + str(check.record_id)
TypeError: unsupported operand type(s) for +: 'bool' and 'str'

```

**Comment by lmignon** [comment]
@guewen I'll use the connector for a project in 9.0. How can I help to the migration? Can I start by making the module installable and may be remove the code related to the _old workers_?

**Comment by guewen** [comment]
@lmignon yes, that's the main things we have to do I think, I added sub-tasks in this issue, so if you think about other things to do it would be nice if you could complete this list. Thanks!

**Comment by lmignon** [comment]
@guewen OK thanks

**Comment by guewen** [comment]
PR: https://github.com/OCA/connector/pull/169

**Comment by parthivgls** [comment]
is this done ? I am planning to start migration of connector-woocommerce and connector-prestashop to v9.

**Comment by guewen** [comment]
@parthivgls yes! connector is working on 9.0 :)

You might need `connector_base_product` which is not migrated yet but it shouldn't be a big deal, it's only a view.

**Comment by SodexisTeam** [comment]
For info we are porting connector_base_product module

**Comment by pedrobaeza** [comment]
Updated in the main section

**Comment by lmignon** [comment]
no more remaining task. Connector is fully migrated to 9.0!
