### ISSUE TITLE
Roadmap v10

### ISSUE THREAD

**Issue by guewen** [OCA/connector#206]
Things to plan for the migration to Odoo 10:
- [x] rename `openerp` occurrences to `odoo` (binder, ...) (merged)
- [x] remove `@api.one` (merged)
- [x] progressively get rid of `ConnectorSession` (merged)
- [x] migrate jobs storage to `json` instead of `pickle` (in OCA/queue)
- [x] allow to find `ConnectorUnits` by a 'service name' when we want a unit on but have no corresponding model (or service name + model) → #231 
- [ ] graph view for jobs
- [x] rethink the backend registry now that we have more experiences (current situation: easy to extend across backends, hard to extend for 1 backend) → #231

**Comment by lasley** [comment]
We should remove `@api.one` as well - it's used a few times in queue handling. This has been confirmed to be deprecated unfortunately.

**Comment by sbidoul** [comment]
@guewen progressively get rid of connector sessions? I tend to think they are now redundant with regular Odoo environments.

We could start with a new decorator that transforms any model method into a delayable job.

**Comment by guewen** [comment]
We should indeed remove the `ConnectorSession`. I think they are 2 features still useful in it: the commit method that do not commit during tests, that might be unnecessary with `openerp.sql_db.TestCursor`? And the ability to change the `Environment`, which might be pulled up to the `ConnectorEnvironment`.

Also, we should probably take this opportunity to migrate from `pickle` to `json` for the jobs storage.

**Comment by lasley** [comment]
v10 might be a time to talk about our testing strategy as a whole. IMO the current strategy is not scalable & the gigantic data file defeats the purpose of unit testing - small isolated cases with no linked dependencies.

My current connectors are purely mock based testing & have been able to achieve solid coverage ([92%](https://coveralls.io/github/laslabs/odoo-connector-carepoint), [91%](https://coveralls.io/github/laslabs/infrastructure-dns)) w/ what seem to really great results in terms of regression catches.

My issue lies in what you solve with the data file, which are the data issues. Due to this, I've been experimenting with [fuzz testing](https://en.wikipedia.org/wiki/Fuzz_testing) with several frameworks:
- [Sulley](https://github.com/OpenRCE/sulley) (my fav so far)
- [Fuzzing](http://fuzzing.readthedocs.io/en/latest/tutorial.html)
- [Fusil](https://pypi.python.org/pypi/fusil/)

IMO a major version upgrade is the time to switch something up like this, so I bring it up. Thoughts?

**Comment by lmignon** [comment]
> I think they are 2 features still useful in it: the commit method that do not commit during tests, that might be unnecessary with openerp.sql_db.TestCursor

@guewen In my tests I disable commit on cr with `self.env.cr.commit = mock.MagicMock()` 

> v10 might be a time to talk about our testing strategy as a whole. IMO the current strategy is not scalable & the gigantic data file defeats the purpose of unit testing - small isolated cases with no linked dependencies.

@lasley The `connector` don't use _gigantic data file_ in the unit tests. The unit tests are small and isolated cases. I suppose that your comment is for the Magento connector and is off topic for the connector itself.

**Comment by lasley** [comment]
@guewen I took the liberty of checking off the two todo's that were implemented in #231, already merged.

Does anyone disagree that v10 should now be the main branch for this repo?

_Edit: I could have sworn the default was still v9 when I posted this comment, but like 2 minutes later it isn't so I'm thinking I'm just stupid and it was a cache thing._

**Comment by guewen** [comment]
@lasley Thanks for the update. Yes it was already 10.0 :)
