### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/connector#440]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

- [x] component - By @asierneiradev - #441
- [x] component_event - By @asierneiradev - #443
- [x] connector - By @asierneiradev - #442
- [x] connector_base_product - By @asierneiradev - #444
- [x] test_component - By @asierneiradev - #441
- [x] test_connector - By @asierneiradev - #442

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by asierneiradev** [comment]
Good afternoon,
I have been working on the migration of the connector repository modules and I would like them to be reviewed.
Attached are the links for each PR, thank you in advance:

**component** and **test_component**: https://github.com/OCA/connector/pull/441
**connector** and **test_connector**: https://github.com/OCA/connector/pull/442
**component_event**: https://github.com/OCA/connector/pull/443
**connector_base_product**: https://github.com/OCA/connector/pull/444

Best regards

**Comment by bizzappdev** [comment]
connector: https://github.com/OCA/connector/pull/447

**Comment by dtorreskaertech** [comment]
This should be close right?
Because all of the related PR has been merged.
